all:
  children:
    isp:
      hosts:
        ISP-CORE1:
          ansible_host: 10.0.0.1
        ISP-PE1:
          ansible_host: 10.0.0.6
        ISP-PE2:
          ansible_host: 10.0.0.10
        ISP-PE3:
          ansible_host: 10.0.0.13
        ISP-EDGE:
          ansible_host: 10.0.0.25
