- name: Test forbindelse til routere
  hosts: isp
  gather_facts: no

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_network_cli_ssh_type: paramiko
    ansible_user: "{{ lookup('env', 'SSHA') }}"
    ansible_password: "{{ lookup('env', 'SSHP') }}"
    ansible_become: false
    ansible_ssh_common_args: "{{ lookup('env', 'SSH_KEX') }}"

  tasks:
    - name: Kør show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: output

    - name: Vis output
      debug:
        var: output.stdout_lines
